name: ambient2.0
channels:
  - pytorch
  - nvidia
dependencies:
  - python>=3.8, < 3.10  # package build failures on 3.10
  - pip
  - numpy>=1.20
  - click>=8.0
  - pillow>=8.3.1
  - scipy>=1.7.1
  - pytorch=2.0.0
  - torchvision
  - psutil
  - requests
  - tqdm
  - imageio
  - s3fs
  - pip:
    - imageio-ffmpeg>=0.4.3
    - pyspng
    - awscli
    - wandb
    - boto3
    - accelerate
    - datasets
    - transformers
    - bitsandbytes